### PR TITLE
adding rich text editor in basic details

### PR DESCRIPTION
**Pull request by sachinkumar579**
#### Changes

- Adding rich text editor in Basic details About section 
- Get basic details values from store and display in resume layout 

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sachinkumar579** [comment]
There is an issue with displaying Summary contents in Resume layout . But it shouldn't stop from deploying.

**Comment by siva-kannan3** [comment]
> There is an issue with displaying Summary contents in Resume layout . But it shouldn't stop from deploying.

will check @sachinkumar579

**Comment by sachinkumar579** [comment]
> > There is an issue with displaying Summary contents in Resume layout . But it shouldn't stop from deploying.
> 
> will check @sachinkumar579

Summary contents are not getting displayed correctly when you edit something in Objective and come back to edit Summary. However, you try editing Summary first , go to Links or Contacts and come back to edit again it will display correctly. 
I guess , store values are not getting updated correctly after editing Objective and coming back to Summary.

**Comment by siva-kannan3** [comment]
> Summary contents are not getting displayed correctly when you edit something in Objective and come back to edit Summary. However, you try editing Summary first , go to Links or Contacts and come back to edit again it will display correctly. I guess , store values are not getting updated correctly after editing Objective and coming back to Summary.

Thanks for the clarification, I also debugged , as you said it is a store issue only, I am working on it, I will let you know once it is done.

**Comment by siva-kannan3** [comment]
These changes are moved in a seperate pr, so closing the PR

**Pull request closed without merging**
