### PR TITLE
Migration of Nextjs & Node support

### PR DESCRIPTION
**Pull request by sadanandpai**
Migration to the latest version of NextJS along with other libraries.

Libraries excluded from upgradation (to be planned in future as they've breaking changes)
- Zustand
- Immer

Dropped items
- Storybook
- Jest

### CODE REVIEW

**Comment by vivek-nexus** [comment]
Some notes. Consider only whatever is relevant. Ignore if intentionally changed.

# General
- Switching between templates takes more than a few seconds First time only.
- Images take relatively more time to load. First time only.
- Markdown editor takes relatively more time to load. First time only.

# UI differences
| Old | New |
| --- | --- |
| image |  image |

**Comment by sadanandpai** [comment]
@vivek-nexus thanks for reviewing.

The delay should be the same even now. Codewise no changes have been made. We might've to do some comparison if there is a change in loading time.

I will work on the UI difference fix today.

**Comment by sadanandpai** [comment]
Updated @vivek-nexus

**Comment by vivek-nexus** [comment]
I don't know if me approving makes any sense, but did it anyway :sweat_smile:

**Pull request merged**
