### PR TITLE
Extend drag to full pill, center delete image

### PR DESCRIPTION
**Pull request by yakshaG**
- Extend drag holder to full pill
- Center "delete" image inside the button
- Set "delete" image width and height to 16px

### CODE REVIEW

**Review by siva-kannan3 — APPROVED** [review]
LGTM

**Comment by yakshaG** [comment]
I introduced one bug. "Delete" button is not working anymore. I dont know how to fix it. Something to do with `listeners` :man_shrugging: 

@siva-kannan3 @gopal1996 @sadanandpai

**Comment by siva-kannan3** [comment]
> I introduced one bug. "Delete" button is not working anymore. I dont know how to fix it. Something to do with `listeners` 🤷‍♂️
> 
> @siva-kannan3 @gopal1996 @sadanandpai

I thought delete wasn't implemented. I will look into it then.

**Comment by siva-kannan3** [comment]
> The listeners property contains the activator event handlers. For instance, when implementing a sortable element with a "drag handle", the ref should be attached to the parent node that should be sortable, but the listeners can be attached to the handle node instead.

@yakshaG The listeners should be passed in drag handle as stated above. Since it has it's own activator event handlers it doesn't allowing the onclick event on delete to function.

For more reference , take a look into this [https://docs.dndkit.com/presets/sortable/usesortable#listeners](https://docs.dndkit.com/presets/sortable/usesortable#listeners)

**Comment by yakshaG** [comment]
> > The listeners property contains the activator event handlers. For instance, when implementing a sortable element with a "drag handle", the ref should be attached to the parent node that should be sortable, but the listeners can be attached to the handle node instead.
> 
> @yakshaG The listeners should be passed in drag handle as stated above. Since it has it's own activator event handlers it doesn't allowing the onclick event on delete to function.
> 
> For more reference , take a look into this https://docs.dndkit.com/presets/sortable/usesortable#listeners

Thanks so much @siva-kannan3 ! I understood that the events were conflicting and only one can be there and not both. So restricted the drag to holder + skill text, which is a good compromise.

This corner case is still not resolved though. I cant fight with flex :grimacing: 
image

**Comment by sadanandpai** [comment]
You can use word break property

**Comment by sadanandpai** [comment]
> > > The listeners property contains the activator event handlers. For instance, when implementing a sortable element with a "drag handle", the ref should be attached to the parent node that should be sortable, but the listeners can be attached to the handle node instead.
> > 
> > 
> > @yakshaG The listeners should be passed in drag handle as stated above. Since it has it's own activator event handlers it doesn't allowing the onclick event on delete to function.
> > For more reference , take a look into this https://docs.dndkit.com/presets/sortable/usesortable#listeners
> 
> Thanks so much @siva-kannan3 ! I understood that the events were conflicting and only one can be there and not both. So restricted the drag to holder + skill text, which is a good compromise.
> 
> This corner case is still not resolved though. I cant fight with flex 😬 image

You can use word break property

**Comment by sadanandpai** [comment]
ou can use word break property

**Pull request merged**
